# escape=`
FROM abrarov/msvc-2022:latest

SHELL ["powershell", "-Command"]
RUN Set-DnsClientServerAddress -InterfaceAlias "Ethernet" -ServerAddresses 8.8.8.8,1.1.1.1; `
    [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12; `
    iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1')); `
    Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1

RUN Set-DnsClientServerAddress -InterfaceAlias "Ethernet" -ServerAddresses 8.8.8.8,1.1.1.1; `
    choco install -y nodejs --version=22.5.1 ; choco install -y cmake


RUN node -v; npm -v

# # Build your addon
# RUN cmake -B build -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release; `
#     cmake --build build --config Release


